#!/bin/bash
id=`xinput list 2> /dev/null | grep 'AT Translated Set 2 keyboard' | awk -F = '{print $2}' | awk '{print $1}'`
slave=`xinput list 2> /dev/null | grep 'AT Translated Set 2 keyboard' | awk -F '(' '{print $2}' | awk -F ')' '{print $1}'`
echo "id=${id}"
echo "slave=${slave}"
sed -i "s/slave= $PARTITION_COLUMN.*/slave=${slave}/" keyboard_on
xinput float $id
